### PR TITLE
Vic/nav re design

### PR DESCRIPTION
**Pull request by vsauceda-cfa**
Here is the new nav, footer, burgeritems redesign

### CODE REVIEW

**Comment by timmalstead-cfa** [comment]
@vsauceda-cfa here are a few notes I have on this pr

Screen Shot 2021-08-25 at 9 25 52 AM

looks like the the way fit the search component in the header has made it unable to display results.

Screen Shot 2021-08-25 at 9 26 47 AM

similarly, it looks like the searchbar no longer readjusts to full width on smaller views

Screen Shot 2021-08-25 at 9 26 58 AM

search results on mobile look like they are not properly centered also.

Screen Shot 2021-08-25 at 9 36 21 AM

getting this error when attempting to size to a larger view from a smaller with search results open

Screen Shot 2021-08-25 at 9 39 29 AM
Screen Shot 2021-08-25 at 9 39 35 AM

This footer is twice the size of the viewport on mobile. Can we make it more compact?

Screen Shot 2021-08-25 at 9 26 03 AM

Lastly, I don't think this necessarily needs to be its own page if it's just a link out to an external resource. What do you think?

**Comment by timmalstead-cfa** [comment]
@vsauceda-cfa 

It looks like the failing tests on `Header` are mostly just a mismatch of it expecting the content from before you changed it and you supplying new content. It should be pretty easy to get in there and change the number of nodes it expects and also the specific text content it expects. As for the test where it is saying that a role is inaccessible, I think that is being hidden on the DOM because of a media shift. Do we still need that element/role or does it not have a place in your new layout? 

Also, since it looks like it's just the header that is presenting problems, you can run `yarn jest __tests__/components/Header.test.tsx --coverage` to just target the element in question.

**Comment by timmalstead-cfa** [comment]
@vsauceda-cfa did you want to add the dropdown menus to the footer or do you think we should merge it as it presently is?

**Comment by vsauceda-cfa** [comment]
> @vsauceda-cfa did you want to add the dropdown menus to the footer or do you think we should merge it as it presently is?

Were you thinking of adding the dropdowns on the desktop view or were you referring to smaller views?

**Comment by timmalstead-cfa** [comment]
@vsauceda-cfa I think that the drop downs would look nice on the mobile views as well as the desktop, but I'm not married to it. I would say go with what you think looks best.

**Pull request merged**
