### PR TITLE
Vic/mobile app bar

### PR DESCRIPTION
**Pull request by vsauceda-cfa**
Fixed the footer issue.

### CODE REVIEW

**Comment by timmalstead-cfa** [comment]
I don't think that adding a margin around the list and map components is the best use of our space.

Screen Shot 2021-07-22 at 11 44 41 AM

I think how we had it before was a better setup

Screen Shot 2021-07-22 at 11 45 00 AM

**Comment by timmalstead-cfa** [comment]
Similar to above, I don't think that having an icon, some text and the filters adds much more than having immediate access to the map and list. also, it makes the user scroll more to get to the useful content.

Screen Shot 2021-07-22 at 11 49 38 AM

since we are not using the latter two filters, maybe we could combine the two concepts into something like this?

idea

**Comment by timmalstead-cfa** [comment]
I don't think the pattern of hiding and revealing the list, map and filter is the best way to do it. Especially with the map. From what I can tell it looks like it is unloading and reloading the map on the DOM each time the map is revealed.

Here is page and network tab before I load the map

Screen Shot 2021-07-22 at 12 11 08 PM

and after I reveal the map

Screen Shot 2021-07-22 at 12 11 25 PM

back to the list

Screen Shot 2021-07-22 at 12 11 35 PM

and loading the map again

Screen Shot 2021-07-22 at 12 11 49 PM

as you can see, it is reloading the same resources each time the map is revealed.

It also seems to be reloading the map when the window is resized from a mobile sized view to a full sized view.

Right now in the application, I have the list and map help in `details` tags. toggling these on and off does not trigger a data reload, it merely changes the visibility and spacing of the document. Is it possible we could do something closer to that?

**Comment by timmalstead-cfa** [comment]
I think the app bar is coming together very well. Could we do something on where it delivers the results from bottom up, like this?

mobile app bar

**Comment by timmalstead-cfa** [comment]
@timmalstead-cfa @vsauceda-cfa here are my initial thoughts for this. I haven't gone deep into the state and mechanics of the filtering just yet. Please let me know your thoughts when you've a moment. Thanks!

**Comment by vsauceda-cfa** [comment]
> I don't think that adding a margin around the list and map components is the best use of our space.
> 
> Screen Shot 2021-07-22 at 11 44 41 AM
> 
> I think how we had it before was a better setup
> 
> Screen Shot 2021-07-22 at 11 45 00 AM

Hmm yeah I can Re adjust the margins. Not intentional. prolly when I was messing with mobile

**Comment by vsauceda-cfa** [comment]
> Similar to above, I don't think that having an icon, some text and the filters adds much more than having immediate access to the map and list. also, it makes the user scroll more to get to the useful content.
> 
> Screen Shot 2021-07-22 at 11 49 38 AM
> 
> since we are not using the latter two filters, maybe we could combine the two concepts into something like this?
> 
> idea

Screen Shot 2021-07-22 at 1 15 17 PM

On the wire  frames it has the name and description on the image above. I was going off that. Happy to remove them if needed. We might want to let Jeanmarie know. 211 app also has them the same as wireframes with descriptions

**Pull request closed without merging**
